Repository anshjindal/wouessi-ems-frontend, pull requests merged in 2025-04, with the labels that each got.

#70 This is for the frontend of the milestone task
  README.md
  src/assets/images/Milestones.png
  src/components/AddMilestoneForm.jsx
  src/components/AddTaskForm.jsx
  src/components/MilestoneList.jsx
  src/components/TasksList.jsx
  src/pages/Dashboard/Dashboard.jsx
  src/pages/MIlestones.jsx
Labels: ems210

#69 Updated timesheets
  src/pages/timesheets/Timesheets.jsx
Labels: ems209

#66 Feat 86a7h8u09: Add Document Upload for Team Members
  src/Router.jsx
  src/components/forms/TeamMemberForm.jsx
  src/components/modals/TeamMemberUpdateModal.jsx
  src/pages/TeamManagement/TeamManagement.jsx
  src/services/teamService.js
  src/styles/pages/TeamMemberManagement.css
Labels: ems211

#46 Feat ems 211 86a7kczwb: Authentication and Database Configuration Frontend Updates
  .dockerignore
  .env
  Dockerfile
  nginx.conf
  package.json
  src/services/authService.js
  src/services/employeeService.js
  tatus -u
Labels: ems211
