Repository anshjindal/wouessi-ems-frontend, pull requests merged in 2025-03, with the labels that each got.

#15 Feat 86a7hahqc: Added role filtering to employee management table
  src/pages/EmployeeManagement/EmployeeManagement.jsx
  src/styles/pages/EmployeeManagement.css
Labels: ems212

#21 feat(teams): add team management components frontend updates
  src/pages/Dashboard/Dashboard.jsx
  src/pages/Leaves/Leaves.jsx
  src/pages/Profile/Profile.jsx
  src/services/employeeService.js
  src/services/leavesService.js
Labels: ems211

#22 feat(Timesheet): Added Timesheet functionality on front end 506f704c80f32428bda44740c60e8c329fb00460
  src/Router.jsx
  src/pages/Timesheet/Timesheet.css
  src/pages/Timesheet/Timesheet.jsx
  src/services/timesheetService.js
Labels: ems211

#23 EMS 209 - Add Timesheets, Entry logs & Date picker - 86a7gwuwa
  setup-remote.bat
  setup-remote.sh
  src/Router.jsx
  src/pages/Timesheets/Timesheets.jsx
  src/styles/pages/Timesheets.css
Labels: ems209

#26 feat 86a7g7mnx: [Devops#2] CI Pipeline Setup in Jenkins
  cicd/ems_212/Dockerfile
  cicd/ems_212/Jenkinsfile
  cicd/ems_212/k8s/deployment.yaml
  cicd/ems_212/k8s/ingress.yaml
  cicd/ems_212/k8s/service.yaml
Labels: ems212

#27 Feat 86a7http2: Add Document
  src/Router.jsx
  src/components/forms/DocumentSubmissionForm.jsx
  src/styles/components/DocumentSubmissionForm.css
Labels: ems210

#33 Feat 86a7htrnm - Added offboarding to dashboard and sidebar
  src/Router.jsx
  src/assets/images/Offboarding.jpg
  src/pages/Dashboard/Dashboard.jsx
  src/pages/Offboarding/OffboardingPage.jsx
  src/styles/pages/OffboardingPage.css
Labels: ems302

#29 feat(devops): set up jenkins pipeline for frontend
  Jenkinsfile
  eslintrc.js
  package.json
  setup-remote.bat
  setup-remote.sh
Labels: ems211

#24 SendBulkCertButton
  Wouessi-frontend/src/pages/EmployeeManagement/EmployeeManagement.jsx
Labels: ems212

#30 Ems 212 task 86a7hahrq
  Label/index.html
  Label/script.js
  Label/script.js .js
  index
  setup-remote.bat
  setup-remote.sh
Labels: ems212

#25 Feat : 86a7gwxcg
  src/Router.jsx
  src/components/tables/SubmittedTimesheetsTable.jsx
  src/pages/Timesheets/SubmittedTimesheets.jsx
  src/styles/components/SubmittedTimesheetsTable.css
Labels: ems209

#31 feat 86a7gx03j: Added accessibility to timesheet form
  src/pages/Timesheets/Timesheets.jsx
Labels: ems209

#35 Feat task 86a7gwx8j: Created functionality to save timesheet to database on frontend
  src/pages/Timesheets/Timesheets.jsx
  src/services/timesheetService.js
Labels: ems209

#32 Onboarding UI form
  .env
  src/pages/Dashboard/Onboarding.js
  src/styles/pages/Onboarding.css
Labels: ems211

#34 Feat task 86a7gx081: Add accessibility for timesheet table.
  src/Router.jsx
  src/components/tables/SubmittedTimesheetsTable.jsx
Labels: ems209

#39 86a7gwxty and 86a7gwxje: Implement Timesheet Approval and Rejection with Comments & UI Enhancements
  TimeSheetApproval.html
Labels: ems209

#44 Added Docker Integrations
  cicd_team_ems209/.dockerignore
  cicd_team_ems209/dockerfile
  cicd_team_ems209/jenkinsfile
Labels: ems209

#55 86a7gy213| EMS 208 | Added loading indicators/state for tables
  .env
  package-lock.json
  src/components/common/LoadingSpinner.jsx
  src/pages/Dashboard/Dashboard.jsx
  src/pages/EmployeeManagement/EmployeeManagement.jsx
  src/pages/ForgotPassword/ForgotPassword.jsx
  src/pages/Leaves/LeaveRequests.jsx
  src/pages/Login/Login.jsx
  src/pages/Profile/Profile.jsx
  src/styles/components/LoadingSpinner.css
Labels: ems208

#59 Add Profile Picture Upload
  package-lock.json
  package.json
  setup-remote.bat
  setup-remote.sh
  src/App.test.js
  src/pages/Profile/Profile.jsx
  src/services/employeeService.js
  src/styles/pages/Profile.css
Labels: ems208

#47 Add certificate table component - 86a7hc85r
  src/components/table/CertificateTable.jsx
Labels: ems212

#49 Added certificate preview feature
  src/CertificatePreview.jsx
Labels: ems212

#54 Add Selection Functionality for Bulk Actions
  86a7ha0e1/Deselect_All.js
  86a7ha0e1/checkbox.html 
  86a7hahjw/generate_for_select.html
  86a7hahjw/stimulate_generation.js
Labels: ems212

#62 feat(scope): Bulk Reactivation Button 86a7h8uuk and feat(scope): Display Partner Details in Table 86a7h8rk7
  package-lock.json
  package.json
  src/pages/EmployeeManagement/EmployeeManagement.jsx
  src/services/employeeService.js
Labels: ems211

#43 Task 86a7htrnn - Create an offboarding process form only for accounts with admin permissions
  src/Router.jsx
  src/components/forms/OffboardingForm.jsx
  src/pages/Dashboard/Dashboard.jsx
  src/pages/Offboarding/OffboardingPage.jsx
  src/styles/components/OffboardingForm.css
  src/styles/pages/OffboardingPage.css
Labels: ems302
